// Parses raw OBD-II mode 03 (Read DTCs) hex responses into structured trouble codes.
// DTC format per SAE J2012: first nibble encodes system (P/B/C/U),
// remaining digits form the numeric code.

export type DtcSystem = 'P' | 'B' | 'C' | 'U';
export type DtcSeverity = 'critical' | 'warning' | 'info';

export interface ParsedDtc {
  readonly code: string;       // e.g. "P0300"
  readonly system: DtcSystem;
  readonly description: string;
  readonly severity: DtcSeverity;
}

// Maps the two high bits of the first DTC byte to the system letter
const SYSTEM_MAP: Readonly<Record<number, DtcSystem>> = {
  0: 'P',
  1: 'C',
  2: 'B',
  3: 'U',
};

// Converts a two-byte hex pair (e.g. "03", "00") to a DTC code string ("P0300")
function bytesToDtcCode(highByte: string, lowByte: string): string {
  const high = parseInt(highByte, 16);
  const low = parseInt(lowByte, 16);

  if (isNaN(high) || isNaN(low)) {
    throw new Error(`Invalid DTC bytes: "${highByte}" "${lowByte}"`);
  }

  // Upper 2 bits of high byte determine the system
  const systemIndex = (high >> 6) & 0x03;
  const system = SYSTEM_MAP[systemIndex] ?? 'P';

  // Lower 6 bits of high byte + full low byte = 3-digit hex code
  const numericPart = ((high & 0x3f) << 8) | low;
  const digits = numericPart.toString(16).toUpperCase().padStart(4, '0');

  return `${system}${digits}`;
}

// Assigns severity based on the DTC code range.
// These are conservative heuristics — a full DTC database lookup would be more accurate.
export function classifySeverity(code: string): DtcSeverity {
  const numeric = parseInt(code.slice(1), 16);

  // P0 series: powertrain generic — most are warnings, some are critical
  if (code.startsWith('P0')) {
    // Misfire, fuel system, O2 sensor, catalyst codes → critical
    if (numeric >= 0x0100 && numeric <= 0x0199) return 'critical'; // fuel/air metering
    if (numeric >= 0x0300 && numeric <= 0x0399) return 'critical'; // misfire
    if (numeric >= 0x0A00 && numeric <= 0x0AFF) return 'critical'; // control module
    return 'warning';
  }

  // P2 series: fuel system (P20xx injectors, P23xx-P27xx diesel)
  if (code.startsWith('P2')) {
    // P23xx-P27xx: diesel injection/glow plugs — critical for diesel engines
    if (numeric >= 0x2300 && numeric <= 0x27FF) return 'critical';
    // P20xx: fuel injectors → critical
    if (numeric >= 0x2000 && numeric <= 0x20FF) return 'critical';
    // P25xx-P26xx: other fuel system components
    if (numeric >= 0x2500 && numeric <= 0x26FF) return 'warning';
    return 'warning';
  }

  // P3-P6 series: mostly warnings (ignition, emissions, sensors, transmission)
  if (code.startsWith('P3') || code.startsWith('P4') || code.startsWith('P5') || code.startsWith('P6')) {
    return 'warning';
  }

  // B/C/U codes: body, chassis, network — usually informational
  if (code.startsWith('B') || code.startsWith('C') || code.startsWith('U')) {
    return 'info';
  }
  return 'warning';
}

// Built-in descriptions for OBD-II codes (SAE J1979-1 standard).
// ~400 common codes covering P/B/C/U systems. The LLM layer enriches these at runtime.
// Priority: P0xxx (powertrain), P23xx-P27xx (diesel fuel systems), P2xxx (fuel/injection),
// and B/C/U codes for body/chassis/network diagnostics.
const COMMON_DTC_DESCRIPTIONS: Readonly<Record<string, string>> = {
  // P01xx: Fuel/Air Metering
  P0100: 'Mass Air Flow Circuit Malfunction',
  P0101: 'MAF Circuit Range/Performance',
  P0102: 'MAF Circuit Low Input',
  P0103: 'MAF Circuit High Input',
  P0104: 'MAF Circuit Intermittent',
  P0105: 'Manifold Absolute Pressure/Barometric Pressure Circuit Malfunction',
  P0106: 'MAP/Baro Circuit Range/Performance',
  P0107: 'MAP/Baro Circuit Low Input',
  P0108: 'MAP/Baro Circuit High Input',
  P0109: 'MAP/Baro Circuit Intermittent',
  P0110: 'Intake Air Temperature Circuit Malfunction',
  P0111: 'IAT Circuit Range/Performance',
  P0112: 'IAT Circuit Low Input',
  P0113: 'IAT Circuit High Input',
  P0114: 'IAT Circuit Intermittent',
  P0115: 'Engine Coolant Temperature Circuit Malfunction',
  P0116: 'ECT Circuit Range/Performance',
  P0117: 'ECT Circuit Low Input',
  P0118: 'ECT Circuit High Input',
  P0119: 'ECT Circuit Intermittent',
  P0120: 'Throttle/Pedal Position Sensor Circuit Malfunction',
  P0121: 'TPS Circuit Range/Performance',
  P0122: 'TPS Circuit Low Input',
  P0123: 'TPS Circuit High Input',
  P0124: 'TPS Circuit Intermittent',
  P0125: 'Excessive Time to Enter Closed Loop',
  P0128: 'Coolant Thermostat Control Circuit',
  P0129: 'Barometric Pressure Too Low',
  P0130: 'O2 Sensor Circuit (Bank 1 Sensor 1)',
  P0131: 'O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)',
  P0132: 'O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)',
  P0133: 'O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)',
  P0134: 'O2 Sensor Circuit No Activity (Bank 1 Sensor 1)',
  P0135: 'O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1)',
  P0136: 'O2 Sensor Circuit (Bank 1 Sensor 2)',
  P0140: 'O2 Sensor Circuit No Activity (Bank 2 Sensor 1)',
  P0141: 'O2 Sensor Heater Circuit (Bank 2 Sensor 1)',
  P0150: 'O2 Sensor Circuit (Bank 2 Sensor 1)',
  P0151: 'O2 Sensor Circuit Low Voltage (Bank 2 Sensor 1)',
  P0152: 'O2 Sensor Circuit High Voltage (Bank 2 Sensor 1)',
  P0153: 'O2 Sensor Circuit Slow Response (Bank 2 Sensor 1)',
  P0155: 'O2 Sensor Heater Circuit (Bank 2 Sensor 1)',
  P0160: 'O2 Sensor Circuit (Bank 2 Sensor 2)',
  P0161: 'O2 Sensor Heater Circuit (Bank 2 Sensor 2)',
  P0171: 'System Too Lean (Bank 1)',
  P0172: 'System Too Rich (Bank 1)',
  P0173: 'System Too Lean (Bank 2)',
  P0174: 'System Too Rich (Bank 2)',
  P0175: 'System Too Rich',
  P0176: 'Fuel Composition Sensor Circuit Malfunction',
  P0177: 'Fuel Composition Sensor Circuit Range/Performance',
  P0178: 'Fuel Composition Sensor Circuit Low Input',
  P0179: 'Fuel Composition Sensor Circuit High Input',
  P0180: 'Fuel Temperature Sensor A Circuit Malfunction',
  P0181: 'Fuel Temperature Sensor A Circuit Range/Performance',
  P0182: 'Fuel Temperature Sensor A Circuit Low Input',
  P0183: 'Fuel Temperature Sensor A Circuit High Input',

  // P02xx: Fuel Injector Circuit
  P0201: 'Injector Circuit Malfunction — Cylinder 1',
  P0202: 'Injector Circuit Malfunction — Cylinder 2',
  P0203: 'Injector Circuit Malfunction — Cylinder 3',
  P0204: 'Injector Circuit Malfunction — Cylinder 4',
  P0205: 'Injector Circuit Malfunction — Cylinder 5',
  P0206: 'Injector Circuit Malfunction — Cylinder 6',
  P0207: 'Injector Circuit Malfunction — Cylinder 7',
  P0208: 'Injector Circuit Malfunction — Cylinder 8',
  P0209: 'Injector Circuit Malfunction — Cylinder 9',
  P0210: 'Injector Circuit Malfunction — Cylinder 10',
  P0211: 'Injector Circuit Malfunction — Cylinder 11',
  P0212: 'Injector Circuit Malfunction — Cylinder 12',
  P0213: 'Cold Start Injector 1 Malfunction',
  P0214: 'Cold Start Injector 2 Malfunction',
  P0215: 'Engine Shutoff Solenoid Malfunction',
  P0216: 'Injection Timing Control Circuit Malfunction',
  P0217: 'Engine Over Temperature Condition',
  P0218: 'Transmission Over Temperature Condition',
  P0219: 'Engine Overspeed Condition',
  P0220: 'Throttle/Pedal Position Sensor B Circuit Malfunction',
  P0221: 'TPS B Circuit Range/Performance',
  P0222: 'TPS B Circuit Low Input',
  P0223: 'TPS B Circuit High Input',
  P0224: 'TPS B Circuit Intermittent',
  P0225: 'Throttle/Pedal Position Sensor C Circuit',
  P0226: 'TPS C Circuit Range/Performance',
  P0227: 'TPS C Circuit Low Input',
  P0228: 'TPS C Circuit High Input',
  P0229: 'TPS C Circuit Intermittent',

  // P23xx: Injection Pump Fuel Metering Control (DIESEL)
  P2300: 'Injection Pump Fuel Metering Control A Circuit Malfunction',
  P2301: 'Injection Pump Fuel Metering Control A Circuit High',
  P2302: 'Injection Pump Fuel Metering Control A Circuit Low',
  P2303: 'Injection Pump Fuel Metering Control B Circuit Malfunction',
  P2304: 'Injection Pump Fuel Metering Control B Circuit High',
  P2305: 'Injection Pump Fuel Metering Control B Circuit Low',
  P2306: 'Injection Pump Fuel Metering Control C Circuit Malfunction',
  P2307: 'Injection Pump Fuel Metering Control C Circuit High',
  P2308: 'Injection Pump Fuel Metering Control C Circuit Low',

  // P25xx-P27xx: Diesel/Fuel System (expanded)
  P2500: 'Engine Speed Output Circuit Malfunction',
  P2501: 'Engine Speed Output Circuit Range/Performance',
  P2502: 'Engine Speed Output Circuit Low',
  P2503: 'Engine Speed Output Circuit High',
  P2504: 'Engine Speed Output Circuit Intermittent',
  P2505: 'Idle Air Control System Malfunction',
  P2506: 'Idle Air Control System Range/Performance',
  P2507: 'Idle Air Control System High',
  P2508: 'Idle Air Control System Low',
  P2509: 'Idle Air Control System Intermittent',
  P2510: 'Idle Control Motor Response Monitor',
  P2511: 'Idle Control Motor Response Monitor',
  P2512: 'Glow Plug Control Module to PCM Communication Malfunction',
  P2513: 'Glow Plug Control Module to PCM Communication Circuit High',
  P2514: 'Glow Plug Control Module to PCM Communication Circuit Low',
  P2515: 'Glow Plug Control Module to PCM Communication Circuit Intermittent',
  P2516: 'Glow Plug Control Module Check Engine Lamp Request Malfunction',
  P2517: 'Glow Plug Control Module to Glow Plug Feedback Wire Malfunction',
  P2518: 'Diesel Glow Plug System Control Module Failure',
  P2519: 'Glow Plug Control Module Power Supply Malfunction',
  P2520: 'Glow Plug Control Module Commanded On When Not Allowed',
  P2521: 'Diesel Particulate Filter Soot Accumulation',
  P2522: 'Diesel Particulate Filter Cleaning Not Performed',
  P2523: 'Diesel Particulate Filter Conditions Not Met for Cleaning',
  P2524: 'Diesel Particulate Filter Regeneration Inhibited by Engine Temperature',
  P2525: 'Diesel Particulate Filter Regeneration Inhibited by Vehicle Speed',
  P2526: 'Diesel Particulate Filter Regeneration Inhibited by Accelerator Pedal',
  P2527: 'Diesel Particulate Filter Regeneration Inhibited by Transmission Temperature',
  P2528: 'Diesel Particulate Filter Regeneration Inhibited by Transmission Gear',
  P2529: 'Diesel Particulate Filter Regeneration Inhibited by Engine Oil Temperature',

  // P03xx: Ignition System
  P0300: 'Random/Multiple Cylinder Misfire Detected',
  P0301: 'Cylinder 1 Misfire Detected',
  P0302: 'Cylinder 2 Misfire Detected',
  P0303: 'Cylinder 3 Misfire Detected',
  P0304: 'Cylinder 4 Misfire Detected',
  P0305: 'Cylinder 5 Misfire Detected',
  P0306: 'Cylinder 6 Misfire Detected',
  P0307: 'Cylinder 7 Misfire Detected',
  P0308: 'Cylinder 8 Misfire Detected',
  P0309: 'Cylinder 9 Misfire Detected',
  P0310: 'Cylinder 10 Misfire Detected',
  P0311: 'Cylinder 11 Misfire Detected',
  P0312: 'Cylinder 12 Misfire Detected',
  P0313: 'Misfire Detected with Low Fuel',
  P0314: 'Single Cylinder Misfire',
  P0320: 'Ignition/Distributor Engine Speed Input Circuit Malfunction',
  P0321: 'Ignition/Distributor Engine Speed Input Circuit Range/Performance',
  P0322: 'Ignition/Distributor Engine Speed Input Circuit No Signal',
  P0323: 'Ignition/Distributor Engine Speed Input Circuit Intermittent',
  P0325: 'Knock Sensor Circuit Malfunction (Bank 1)',
  P0326: 'Knock Sensor Circuit Range/Performance (Bank 1)',
  P0327: 'Knock Sensor Circuit Low Input (Bank 1)',
  P0328: 'Knock Sensor Circuit High Input (Bank 1)',
  P0329: 'Knock Sensor Circuit Input Intermittent (Bank 1)',
  P0330: 'Knock Sensor Circuit Malfunction (Bank 2)',
  P0331: 'Knock Sensor Circuit Range/Performance (Bank 2)',
  P0332: 'Knock Sensor Circuit Low Input (Bank 2)',
  P0333: 'Knock Sensor Circuit High Input (Bank 2)',
  P0334: 'Knock Sensor Circuit Input Intermittent (Bank 2)',
  P0335: 'Crankshaft Position Sensor Circuit Malfunction',
  P0336: 'Crankshaft Position Sensor Circuit Range/Performance',
  P0337: 'Crankshaft Position Sensor Circuit Low Input',
  P0338: 'Crankshaft Position Sensor Circuit High Input',
  P0339: 'Crankshaft Position Sensor Circuit Intermittent',
  P0340: 'Camshaft Position Sensor Circuit Malfunction',
  P0341: 'Camshaft Position Sensor Circuit Range/Performance',
  P0342: 'Camshaft Position Sensor Circuit Low Input',
  P0343: 'Camshaft Position Sensor Circuit High Input',
  P0344: 'Camshaft Position Sensor Circuit Intermittent',
  P0350: 'Ignition Coil Primary/Secondary Circuit Malfunction',
  P0351: 'Ignition Coil A Primary/Secondary Circuit',
  P0352: 'Ignition Coil B Primary/Secondary Circuit',
  P0353: 'Ignition Coil C Primary/Secondary Circuit',
  P0354: 'Ignition Coil D Primary/Secondary Circuit',
  P0355: 'Ignition Coil E Primary/Secondary Circuit',
  P0356: 'Ignition Coil F Primary/Secondary Circuit',
  P0357: 'Ignition Coil G Primary/Secondary Circuit',
  P0358: 'Ignition Coil H Primary/Secondary Circuit',
  P0359: 'Ignition Coil I Primary/Secondary Circuit',
  P0360: 'Ignition Coil J Primary/Secondary Circuit',
  P0361: 'Ignition Coil K Primary/Secondary Circuit',
  P0362: 'Ignition Coil L Primary/Secondary Circuit',
  P0363: 'Misfire During Crank',
  P0364: 'Misfire Detected with Low Fuel Level',
  P0365: 'Camshaft Position Sensor B Circuit (Bank 1)',
  P0366: 'Camshaft Position Sensor B Circuit Range/Performance (Bank 1)',
  P0367: 'Camshaft Position Sensor B Circuit Low Input (Bank 1)',
  P0368: 'Camshaft Position Sensor B Circuit High Input (Bank 1)',
  P0369: 'Camshaft Position Sensor B Circuit Intermittent (Bank 1)',
  P0370: 'Timing Reference High Resolution Signal A',
  P0371: 'Timing Reference High Resolution Signal A Too Many Pulses',
  P0372: 'Timing Reference High Resolution Signal A Too Few Pulses',
  P0373: 'Timing Reference High Resolution Signal A Intermittent/Erratic Pulses',
  P0374: 'Timing Reference High Resolution Signal B No Pulses',
  P0375: 'Timing Reference High Resolution Signal B',
  P0376: 'Timing Reference High Resolution Signal B Too Many Pulses',
  P0377: 'Timing Reference High Resolution Signal B Too Few Pulses',
  P0378: 'Timing Reference High Resolution Signal B Intermittent/Erratic Pulses',
  P0379: 'Timing Reference High Resolution Signal B No Pulses',
  P0380: 'Glow Plug Heater Control Circuit Malfunction',
  P0381: 'Glow Plug Heater Control Circuit High',
  P0382: 'Glow Plug Heater Control Circuit Low',
  P0385: 'Crankshaft Position Sensor B Circuit Malfunction',
  P0386: 'Crankshaft Position Sensor B Circuit Range/Performance',
  P0387: 'Crankshaft Position Sensor B Circuit Low Input',
  P0388: 'Crankshaft Position Sensor B Circuit High Input',
  P0389: 'Crankshaft Position Sensor B Circuit Intermittent',
  P0390: 'Camshaft Position Sensor B Circuit (Bank 2)',
  P0391: 'Camshaft Position Sensor B Circuit Range/Performance (Bank 2)',
  P0392: 'Camshaft Position Sensor B Circuit Low Input (Bank 2)',
  P0393: 'Camshaft Position Sensor B Circuit High Input (Bank 2)',
  P0394: 'Camshaft Position Sensor B Circuit Intermittent (Bank 2)',
  P0395: 'Crankshaft Position Sensor C Circuit Malfunction',
  P0396: 'Crankshaft Position Sensor C Circuit Range/Performance',

  // P04xx: Emission Control
  P0400: 'EGR System Malfunction',
  P0401: 'EGR Flow Insufficient',
  P0402: 'EGR Flow Excessive',
  P0403: 'EGR Control Circuit Malfunction',
  P0404: 'EGR Control Circuit Range/Performance',
  P0405: 'EGR Sensor A Circuit Low',
  P0406: 'EGR Sensor A Circuit High',
  P0407: 'EGR Sensor B Circuit Low',
  P0408: 'EGR Sensor B Circuit High',
  P0409: 'EGR Sensor Circuit Malfunction',
  P0410: 'Secondary Air Injection System Malfunction',
  P0411: 'Secondary Air Injection System Incorrect Flow',
  P0412: 'Secondary Air Injection System Control Circuit Malfunction',
  P0413: 'Secondary Air Injection System Control Circuit Open',
  P0414: 'Secondary Air Injection System Control Circuit Shorted',
  P0415: 'Secondary Air Injection System Solenoid A Circuit Malfunction',
  P0416: 'Secondary Air Injection System Solenoid A Circuit Open',
  P0417: 'Secondary Air Injection System Solenoid A Circuit Shorted',
  P0418: 'Secondary Air Injection System Solenoid B Circuit Malfunction',
  P0419: 'Secondary Air Injection System Solenoid B Circuit Open',
  P0420: 'Catalyst System Efficiency Below Threshold (Bank 1)',
  P0421: 'Warm Up Catalyst Efficiency Below Threshold (Bank 1)',
  P0422: 'Main Catalyst Efficiency Below Threshold (Bank 1)',
  P0423: 'Heated Catalyst Efficiency Below Threshold (Bank 1)',
  P0424: 'Heated Catalyst Temperature Below Threshold (Bank 1)',
  P0430: 'Catalyst System Efficiency Below Threshold (Bank 2)',
  P0431: 'Warm Up Catalyst Efficiency Below Threshold (Bank 2)',
  P0432: 'Main Catalyst Efficiency Below Threshold (Bank 2)',
  P0433: 'Heated Catalyst Efficiency Below Threshold (Bank 2)',
  P0434: 'Heated Catalyst Temperature Below Threshold (Bank 2)',
  P0440: 'Evaporative Emission Control System Malfunction',
  P0441: 'EVAP System Incorrect Purge Flow',
  P0442: 'EVAP System Small Leak Detected',
  P0443: 'EVAP Purge Control Valve Circuit Malfunction',
  P0444: 'EVAP Purge Control Valve Circuit Open',
  P0445: 'EVAP Purge Control Valve Circuit Shorted',
  P0446: 'EVAP Vent Control Circuit Malfunction',
  P0447: 'EVAP Vent Control Circuit Open',
  P0448: 'EVAP Vent Control Circuit Shorted',
  P0449: 'EVAP Purge Valve Control Circuit',
  P0450: 'Fuel Tank Pressure Sensor Circuit Malfunction',
  P0451: 'Fuel Tank Pressure Sensor Circuit Range/Performance',
  P0452: 'Fuel Tank Pressure Sensor Circuit Low Input',
  P0453: 'Fuel Tank Pressure Sensor Circuit High Input',
  P0454: 'Fuel Tank Pressure Sensor Circuit Intermittent',
  P0455: 'EVAP System Large Leak Detected',
  P0456: 'EVAP System Very Small Leak Detected',
  P0457: 'EVAP System Leak Detected (Fuel Cap)',
  P0458: 'EVAP Purge Control Valve Circuit Low',
  P0459: 'EVAP Purge Control Valve Circuit High',
  P0460: 'Fuel Level Sensor Circuit Malfunction',
  P0461: 'Fuel Level Sensor Circuit Range/Performance',
  P0462: 'Fuel Level Sensor Circuit Low Input',
  P0463: 'Fuel Level Sensor Circuit High Input',
  P0464: 'Fuel Level Sensor Circuit Intermittent',
  P0465: 'EVAP Vent Fan Control Circuit Malfunction',
  P0466: 'EVAP Vent Fan Control Circuit Range/Performance',
  P0467: 'EVAP Vent Fan Control Circuit Low',
  P0468: 'EVAP Vent Fan Control Circuit High',
  P0469: 'EVAP Vent Fan Control Circuit Intermittent',
  P0470: 'Exhaust Pressure Sensor Circuit Malfunction',
  P0471: 'Exhaust Pressure Sensor Circuit Range/Performance',
  P0472: 'Exhaust Pressure Sensor Circuit Low',
  P0473: 'Exhaust Pressure Sensor Circuit High',
  P0474: 'Exhaust Pressure Sensor Circuit Intermittent',
  P0475: 'Exhaust Backpressure Control Valve Malfunction',
  P0476: 'Exhaust Backpressure Control Valve Range/Performance',
  P0477: 'Exhaust Backpressure Control Valve Low',
  P0478: 'Exhaust Backpressure Control Valve High',
  P0479: 'Exhaust Backpressure Control Valve Intermittent',
  P0480: 'Fan Control Circuit Malfunction',
  P0481: 'Fan Control Circuit High',
  P0482: 'Fan Control Circuit Low',
  P0483: 'Fan Sense Circuit Malfunction',
  P0484: 'Cooling Fan Rationality Check',
  P0485: 'Cooling Fan Control Circuit Low',
  P0486: 'EGR Vent Solenoid Control Circuit Malfunction',
  P0487: 'EGR Vent Solenoid Control Circuit High',
  P0488: 'EGR Vent Solenoid Control Circuit Low',
  P0489: 'EGR Control Solenoid Control Circuit Malfunction',
  P0490: 'EGR Control Solenoid Control Circuit High',
  P0491: 'EGR Control Solenoid Control Circuit Low',
  P0492: 'Secondary Air Injection System Bank 1',
  P0493: 'Secondary Air Injection System Bank 2',
  P0494: 'Engine Coolant Fan Control Low',
  P0495: 'Engine Coolant Fan Control High',
  P0496: 'EVAP Purge Control Valve High',
  P0497: 'EVAP Purge Control Valve Low',

  // P05xx: Fuel/Air Metering
  P0500: 'Vehicle Speed Sensor Malfunction',
  P0501: 'VSS Circuit Range/Performance',
  P0502: 'VSS Circuit Low Input',
  P0503: 'VSS Circuit High Input',
  P0504: 'Brake Switch A/B Correlation',
  P0505: 'Idle Control System Malfunction',
  P0506: 'Idle Air Control System Low',
  P0507: 'Idle Air Control System High',
  P0508: 'Idle Air Control System Performance',
  P0509: 'Idle Air Control System Intermittent',
  P0510: 'Closed Throttle Position Switch Malfunction',
  P0511: 'Idle Air Control System Circuit Malfunction',
  P0512: 'Starter Request Circuit Malfunction',
  P0513: 'Incorrect Immobilizer Key',
  P0514: 'Battery Temperature Out of Range',
  P0515: 'Battery Voltage Out of Range',
  P0516: 'Battery Temperature Sensor Circuit Low',
  P0517: 'Battery Temperature Sensor Circuit High',
  P0518: 'Engine Oil Level Too Low',
  P0519: 'Idle Control System Performance',
  P0520: 'Oil Pressure Sensor Circuit Malfunction',
  P0521: 'Oil Pressure Sensor Circuit Range/Performance',
  P0522: 'Oil Pressure Sensor Circuit Low Input',
  P0523: 'Oil Pressure Sensor Circuit High Input',
  P0524: 'Oil Level Too Low',
  P0525: 'Cruise Control System Malfunction',
  P0526: 'Fan Control System Malfunction',
  P0527: 'Fan Control System Low',
  P0528: 'Fan Control System High',
  P0529: 'Fan Control System Intermittent',
  P0530: 'A/C Compressor Clutch Circuit Malfunction',
  P0531: 'A/C Compressor Clutch Circuit Low',
  P0532: 'A/C Compressor Clutch Circuit High',
  P0533: 'A/C Refrigerant Charge Loss',
  P0534: 'A/C System Pressure High',
  P0535: 'A/C Evaporator Temperature Sensor Circuit Malfunction',
  P0536: 'Engine Intake Air Temperature Control System Malfunction',
  P0537: 'Engine Intake Air Temperature Control Low',
  P0538: 'Engine Intake Air Temperature Control High',
  P0539: 'Engine Intake Air Temperature Control Intermittent',
  P0540: 'Intake Manifold Runner Control Solenoid A',
  P0541: 'Intake Manifold Runner Control Solenoid A Low',
  P0542: 'Intake Manifold Runner Control Solenoid A High',
  P0543: 'Intake Manifold Runner Control Solenoid B',
  P0544: 'Exhaust Gas Temperature Sensor Circuit Malfunction',
  P0545: 'Exhaust Gas Temperature Sensor Circuit Low',
  P0546: 'Exhaust Gas Temperature Sensor Circuit High',
  P0550: 'Power Steering Pressure Sensor Circuit Malfunction',
  P0551: 'Power Steering Pressure Sensor Circuit Range/Performance',
  P0552: 'Power Steering Pressure Sensor Circuit Low Input',
  P0553: 'Power Steering Pressure Sensor Circuit High Input',
  P0554: 'Power Steering Pressure Sensor Circuit Intermittent',
  P0560: 'System Voltage Malfunction',
  P0561: 'System Voltage Unstable',
  P0562: 'System Voltage Too Low',
  P0563: 'System Voltage Too High',
  P0564: 'Cruise Control Multi-Function Input Malfunction',
  P0565: 'Cruise Control On Signal Malfunction',
  P0566: 'Cruise Control Off Signal Malfunction',
  P0567: 'Cruise Control Resume Signal Malfunction',
  P0568: 'Cruise Control Set Signal Malfunction',
  P0569: 'Cruise Control Coast Signal Malfunction',
  P0570: 'Cruise Control Accel Signal Malfunction',
  P0571: 'Cruise Control/Brake Switch Circuit Malfunction',
  P0572: 'Cruise Control/Brake Switch Circuit Low',
  P0573: 'Cruise Control/Brake Switch Circuit High',
  P0574: 'Cruise Control System Malfunction',
  P0575: 'Cruise Control Input Circuit Malfunction',
  P0576: 'Cruise Control Input Circuit Low',
  P0577: 'Cruise Control Input Circuit High',
  P0578: 'Cruise Control Multi-Function Input Malfunction',
  P0579: 'Cruise Control Multi-Function Input Range',
  P0580: 'Cruise Control Multi-Function Input Low',
  P0581: 'Cruise Control Multi-Function Input High',
  P0582: 'Cruise Control Actuator Supply Voltage Malfunction',
  P0583: 'Cruise Control Actuator Supply Voltage Low',
  P0584: 'Cruise Control Actuator Supply Voltage High',
  P0585: 'Cruise Control Control Switch Circuit Malfunction',
  P0586: 'Cruise Control Control Switch Circuit Low',
  P0587: 'Cruise Control Control Switch Circuit High',
  P0588: 'Cruise Control Control Switch Circuit Malfunction',
  P0589: 'Cruise Control Control Switch Circuit Low',
  P0590: 'Cruise Control Control Switch Circuit High',

  // P06xx: PCM/ECU
  P0600: 'Serial Communication Link Malfunction',
  P0601: 'Internal Control Module Memory Check Sum Error',
  P0602: 'PCM Programming Error',
  P0603: 'Internal Control Module Keep Alive Memory Error',
  P0604: 'Internal Control Module Random Access Memory Error',
  P0605: 'Internal Control Module Read Only Memory Error',
  P0606: 'PCM/ECM Processor Fault',
  P0607: 'Control Module Performance',
  P0608: 'Control Module VSS Output A',
  P0609: 'Control Module VSS Output B',
  P0610: 'Control Module IO Fault',
  P0611: 'Fuel Injector Control Module Failure',
  P0612: 'PCM Long Term Memory Reset',
  P0613: 'Transmission Control Module Malfunction',
  P0614: 'ECM/PCM Mismatched Modules',
  P0615: 'Starter Motor Circuit Malfunction',
  P0616: 'Starter Motor Circuit Low',
  P0617: 'Starter Motor Circuit High',
  P0618: 'Alternative Fuel Control Module Malfunction',
  P0619: 'PCM/ECM Processor Fault',
  P0620: 'Generator Control Circuit Malfunction',
  P0621: 'Generator Lamp Control Circuit Malfunction',
  P0622: 'Generator Field Control Circuit Malfunction',
  P0623: 'Generator Field Control Circuit Low',
  P0624: 'Generator Field Control Circuit High',
  P0625: 'Fuel Pump Relay Control Circuit Low',
  P0626: 'Fuel Pump Relay Control Circuit High',
  P0627: 'Fuel Pump Control Circuit Malfunction',
  P0628: 'Fuel Pump Control Circuit Low',
  P0629: 'Fuel Pump Control Circuit High',
  P0630: 'VIN Not Programmed in Control Module',
  P0631: 'VIN Mismatch With Immobilizer',
  P0632: 'Odometer Not Programmed',
  P0633: 'Immobilizer Key Not Programmed',
  P0634: 'PCM/ECM Not Programmed',
  P0635: 'Power Steering Control Circuit Malfunction',
  P0636: 'Power Steering Control Circuit Low',
  P0637: 'Power Steering Control Circuit High',
  P0638: 'Throttle Actuator Power Supply Malfunction',
  P0639: 'Throttle Actuator Power Supply Low',
  P0640: 'Auxiliary Heater Relay Control Circuit Malfunction',
  P0641: 'Sensor 1 Supply Voltage A Low',
  P0642: 'Sensor 1 Supply Voltage A High',
  P0643: 'Sensor 1 Supply Voltage B Low',
  P0644: 'Sensor 1 Supply Voltage B High',
  P0645: 'A/C Compressor Clutch Relay Control Circuit Malfunction',
  P0646: 'A/C Compressor Clutch Relay Control Circuit Low',
  P0647: 'A/C Compressor Clutch Relay Control Circuit High',
  P0648: 'Immobilizer Control Module Signal',
  P0649: 'Speed Control Unable to Hold Speed',
  P0650: 'Malfunction Indicator Lamp Control Circuit Malfunction',
  P0651: 'Sensor 2 Supply Voltage A Low',
  P0652: 'Sensor 2 Supply Voltage A High',
  P0653: 'Sensor 2 Supply Voltage B Low',
  P0654: 'Sensor 2 Supply Voltage B High',
  P0655: 'Power Supply Relay Control Circuit Malfunction',
  P0656: 'Fuel Level Indicator Lamp Control Circuit Malfunction',
  P0657: 'Actuator Supply Voltage Low',
  P0658: 'Actuator Supply Voltage High',
  P0659: 'Sensor Supply Voltage Malfunction',
  P0660: 'Intake Manifold Tuning Valve Control Circuit Malfunction',
  P0661: 'Intake Manifold Tuning Valve Control Circuit Low',
  P0662: 'Intake Manifold Tuning Valve Control Circuit High',
  P0663: 'Intake Manifold Tuning Valve Control Circuit Malfunction',
  P0664: 'Intake Manifold Tuning Valve Control Circuit Low',
  P0665: 'Intake Manifold Tuning Valve Control Circuit High',
  P0666: 'PCM 5V Supply Output Low',
  P0667: 'PCM 5V Supply Output High',
  P0668: 'PCM Sensor Supply Voltage Output Low',
  P0669: 'PCM Sensor Supply Voltage Output High',
  P0670: 'Glow Plug Control Module Malfunction',
  P0671: 'Glow Plug 1 Control Circuit',
  P0672: 'Glow Plug 2 Control Circuit',
  P0673: 'Glow Plug 3 Control Circuit',
  P0674: 'Glow Plug 4 Control Circuit',
  P0675: 'Glow Plug 5 Control Circuit',
  P0676: 'Glow Plug 6 Control Circuit',
  P0677: 'Glow Plug 7 Control Circuit',
  P0678: 'Glow Plug 8 Control Circuit',
  P0679: 'Glow Plug 9 Control Circuit',
  P0680: 'Glow Plug 10 Control Circuit',
  P0681: 'Glow Plug Bank 1 Malfunction',
  P0682: 'Glow Plug Bank 2 Malfunction',
  P0683: 'Glow Plug Control Module Malfunction',
  P0684: 'Glow Plug Control Module to PCM Communication Malfunction',
  P0685: 'Engine Control Module Power Relay Control Circuit Malfunction',
  P0686: 'Engine Control Module Power Relay Control Circuit Low',
  P0687: 'Engine Control Module Power Relay Control Circuit High',
  P0688: 'Engine Control Module Power Relay Sense Circuit Low',
  P0689: 'Engine Control Module Power Relay Sense Circuit High',
  P0690: 'Engine Control Module Power Relay Control Circuit Malfunction',
  P0691: 'Cooling Fan Control Circuit Low',
  P0692: 'Cooling Fan Control Circuit High',
  P0693: 'Cooling Fan Solid State Relay Control Circuit Low',
  P0694: 'Cooling Fan Solid State Relay Control Circuit High',
  P0695: 'Engine Control Module Power Relay Control Circuit Malfunction',
  P0696: 'Engine Control Module Power Relay Sense Circuit Low',
  P0697: 'Engine Control Module Power Relay Sense Circuit High',
  P0698: 'Engine Control Module Power Relay Control Circuit Malfunction',
  P0699: 'Engine Control Module Power Relay Control Circuit',

  // P07xx: Transmission
  P0700: 'Transmission Control System Malfunction',
  P0701: 'Transmission Control System Range/Performance',
  P0702: 'Transmission Control System Electrical Malfunction',
  P0703: 'Torque Converter/Brake Interlock Solenoid Control Circuit',
  P0704: 'Clutch Switch Input Malfunction',
  P0705: 'Transmission Range Sensor Circuit Malfunction',
  P0706: 'Transmission Range Sensor Circuit Range/Performance',
  P0707: 'Transmission Range Sensor Circuit Low Input',
  P0708: 'Transmission Range Sensor Circuit High Input',
  P0709: 'Transmission Range Sensor Circuit Intermittent',
  P0710: 'Transmission Fluid Temperature Sensor Circuit Malfunction',
  P0711: 'Transmission Fluid Temperature Sensor Circuit Range/Performance',
  P0712: 'Transmission Fluid Temperature Sensor Circuit Low Input',
  P0713: 'Transmission Fluid Temperature Sensor Circuit High Input',
  P0714: 'Transmission Fluid Temperature Sensor Circuit Intermittent',
  P0715: 'Input/Turbine Speed Sensor Circuit Malfunction',
  P0716: 'Input/Turbine Speed Sensor Circuit Range/Performance',
  P0717: 'Input/Turbine Speed Sensor Circuit No Signal',
  P0718: 'Input/Turbine Speed Sensor Circuit Intermittent',
  P0719: 'Low Reverse Solenoid Control Circuit Low',
  P0720: 'Output Speed Sensor Circuit Malfunction',
  P0721: 'Output Speed Sensor Circuit Range/Performance',
  P0722: 'Output Speed Sensor Circuit No Signal',
  P0723: 'Output Speed Sensor Circuit Intermittent',
  P0724: 'Low Reverse Solenoid Control Circuit High',
  P0725: 'Engine Speed Input Circuit Malfunction',
  P0726: 'Engine Speed Input Circuit Range/Performance',
  P0727: 'Engine Speed Input Circuit No Signal',
  P0728: 'Engine Speed Input Circuit Intermittent',
  P0729: 'Transmission Overspeeding',
  P0730: 'Automatic Transmission Range Malfunction',
  P0731: 'Transmission Range 1 Incorrect',
  P0732: 'Transmission Range 2 Incorrect',
  P0733: 'Transmission Range 3 Incorrect',
  P0734: 'Transmission Range 4 Incorrect',
  P0735: 'Transmission Range 5 Incorrect',
  P0736: 'Transmission Reverse Incorrect',
  P0737: 'Transmission Neutral Incorrect',
  P0738: 'Transmission Park Incorrect',
  P0739: 'Transmission Forward Range Incorrect',
  P0740: 'Torque Converter Clutch Circuit Malfunction',
  P0741: 'Torque Converter Clutch Circuit Performance/Stuck Off',
  P0742: 'Torque Converter Clutch Circuit Stuck On',
  P0743: 'Torque Converter Clutch Circuit Electrical Malfunction',
  P0744: 'Torque Converter Clutch Circuit Intermittent',
  P0745: 'Pressure Control Solenoid Malfunction',
  P0746: 'Pressure Control Solenoid Performance/Stuck Off',
  P0747: 'Pressure Control Solenoid Stuck On',
  P0748: 'Pressure Control Solenoid Electrical Malfunction',
  P0749: 'Pressure Control Solenoid Intermittent',
  P0750: 'Shift Solenoid A Malfunction',
  P0751: 'Shift Solenoid A Performance/Stuck Off',
  P0752: 'Shift Solenoid A Stuck On',
  P0753: 'Shift Solenoid A Electrical Malfunction',
  P0754: 'Shift Solenoid A Intermittent',
  P0755: 'Shift Solenoid B Malfunction',
  P0756: 'Shift Solenoid B Performance/Stuck Off',
  P0757: 'Shift Solenoid B Stuck On',
  P0758: 'Shift Solenoid B Electrical Malfunction',
  P0759: 'Shift Solenoid B Intermittent',
  P0760: 'Shift Solenoid C Malfunction',
  P0761: 'Shift Solenoid C Performance/Stuck Off',
  P0762: 'Shift Solenoid C Stuck On',
  P0763: 'Shift Solenoid C Electrical Malfunction',
  P0764: 'Shift Solenoid C Intermittent',
  P0765: 'Shift Solenoid D Malfunction',
  P0766: 'Shift Solenoid D Performance/Stuck Off',
  P0767: 'Shift Solenoid D Stuck On',
  P0768: 'Shift Solenoid D Electrical Malfunction',
  P0769: 'Shift Solenoid D Intermittent',
  P0770: 'Shift Solenoid E Malfunction',
  P0771: 'Shift Solenoid E Performance/Stuck Off',
  P0772: 'Shift Solenoid E Stuck On',
  P0773: 'Shift Solenoid E Electrical Malfunction',
  P0774: 'Shift Solenoid E Intermittent',
  P0775: 'Pressure Control Solenoid B Malfunction',
  P0776: 'Pressure Control Solenoid B Performance/Stuck Off',
  P0777: 'Pressure Control Solenoid B Stuck On',
  P0778: 'Pressure Control Solenoid B Electrical Malfunction',
  P0779: 'Pressure Control Solenoid B Intermittent',
  P0780: 'Shift Malfunction',
  P0781: '1-2 Shift Malfunction',
  P0782: '2-3 Shift Malfunction',
  P0783: '3-4 Shift Malfunction',
  P0784: '4-5 Shift Malfunction',
  P0785: 'Shift/Timing Solenoid Control Circuit Malfunction',
  P0786: 'Shift/Timing Solenoid Control Circuit Range/Performance',
  P0787: 'Shift/Timing Solenoid Control Circuit Low',
  P0788: 'Shift/Timing Solenoid Control Circuit High',
  P0789: 'Shift/Timing Solenoid Control Circuit Intermittent',
  P0790: 'Normal/Manual Shift Mode Select Circuit Malfunction',
  P0791: 'Intermediate Shaft Speed Sensor Circuit Malfunction',
  P0792: 'Intermediate Shaft Speed Sensor Circuit Range/Performance',
  P0793: 'Intermediate Shaft Speed Sensor Circuit No Signal',
  P0794: 'Intermediate Shaft Speed Sensor Circuit Intermittent',
  P0795: 'Pressure Control Solenoid C Malfunction',
  P0796: 'Pressure Control Solenoid C Performance/Stuck Off',
  P0797: 'Pressure Control Solenoid C Stuck On',
  P0798: 'Pressure Control Solenoid C Electrical Malfunction',
  P0799: 'Pressure Control Solenoid C Intermittent',
};

function describeCode(code: string): string {
  return COMMON_DTC_DESCRIPTIONS[code] ?? `Fault code ${code} — diagnosis required`;
}

// Parses the raw hex string from a mode 03 response.
// Input example: "43 03 02 01 00 00 00 00 00 00"
// "43" = mode 03 response header, followed by pairs of DTC bytes.
// Returns an empty array if no DTCs are stored ("43 00").
export function parseDtcResponse(rawResponse: string): ParsedDtc[] {
  const cleaned = rawResponse
    .replace(/[\r\n>]/g, '')
    .trim()
    .toUpperCase();

  const bytes = cleaned.split(/\s+/).filter(Boolean);

  // Response header is "43", first data byte is the number of DTCs
  if (bytes.length < 2 || bytes[0] !== '43') {
    return [];
  }

  const dtcCount = parseInt(bytes[1] ?? '0', 16);
  if (dtcCount === 0) return [];

  const dtcs: ParsedDtc[] = [];
  // DTC pairs start at index 2
  for (let i = 2; i + 1 < bytes.length; i += 2) {
    const high = bytes[i];
    const low = bytes[i + 1];
    if (high === undefined || low === undefined) break;
    // "0000" is a placeholder — skip it
    if (high === '00' && low === '00') continue;

    const code = bytesToDtcCode(high, low);
    dtcs.push({
      code,
      system: code[0] as DtcSystem,
      description: describeCode(code),
      severity: classifySeverity(code),
    });
  }

  return dtcs;
}
