// C0 spike runner (PLAN-002 v2): launches the harvest worklet on the SAME Bare
// runtime the QVAC SDK worker uses, and probes — granularly — whether
// Hypercore (sodium/storage addons) and Hyperswarm (udx addon) load on-device.
//
// The worklet source lives in p2p/p2p-worklet.mjs; its bundle is generated
// with `npm run p2p:pack` (bare-pack, module graph already verified to resolve
// for android/ios). Metro never sees hypercore here — the bundle runs on Bare.
// This probe still spins its OWN short-lived Worklet (terminated after the run)
// — it tests the substrate in isolation, independent of the shared workletHost.
//
// Usage (from any dev surface, e.g. a Settings debug button):
//   const report = await runP2PSpike();
//   console.log(report); // human-readable pass/fail per step

import { Worklet } from 'react-native-bare-kit';
// Generated by `npm run p2p:pack` — commit alongside the source.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — bare-pack emits an untyped ES module
import bundle from '../../../p2p/p2p-worklet.bundle.mjs';

interface SpikeMsg {
  step: 'ready' | 'core' | 'swarm';
  ok: boolean;
  key?: string;
  blocks?: number;
  err?: string;
}

// The spike protocol is pure-ASCII JSON, so a byte-wise decode is exact and
// avoids TextDecoder (not guaranteed on Hermes) and b4a (untyped) on the RN side.
function bytesToString(data: unknown): string {
  if (typeof data === 'string') return data;
  const arr = data as Uint8Array;
  let s = '';
  for (let i = 0; i < arr.length; i++) s += String.fromCharCode(arr[i]!);
  return s;
}

// Mirror of bytesToString for the write side. BareKitIPC#_write hands
// data.buffer/byteOffset/byteLength straight to the native module, so writes
// MUST be a TypedArray — a plain string throws "Value is undefined, expected
// an Object" asynchronously inside streamx and the command never reaches the
// worklet.
function stringToBytes(s: string): Uint8Array {
  const arr = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) arr[i] = s.charCodeAt(i) & 0xff;
  return arr;
}

const STEP_TIMEOUT_MS = 15_000;

export async function runP2PSpike(): Promise<string> {
  const lines: string[] = [];
  const worklet = new Worklet();

  try {
    // start() is synchronous (void) — readiness is signaled by the worklet's
    // own 'ready' IPC message, which we await below.
    worklet.start('/p2p-worklet.bundle', bundle);
    const { IPC } = worklet;

    let buffer = '';
    const waiters = new Map<string, (msg: SpikeMsg) => void>();

    IPC.on('data', (data) => {
      buffer += bytesToString(data);
      let idx: number;
      while ((idx = buffer.indexOf('\n')) >= 0) {
        const line = buffer.slice(0, idx);
        buffer = buffer.slice(idx + 1);
        try {
          const msg = JSON.parse(line) as SpikeMsg;
          waiters.get(msg.step)?.(msg);
        } catch {
          // ignore malformed lines
        }
      }
    });

    const expect = (step: SpikeMsg['step']): Promise<SpikeMsg> =>
      new Promise((resolve, reject) => {
        const timer = setTimeout(
          () => reject(new Error(`${step}: no reply in ${STEP_TIMEOUT_MS}ms`)),
          STEP_TIMEOUT_MS,
        );
        waiters.set(step, (msg) => {
          clearTimeout(timer);
          waiters.delete(step);
          resolve(msg);
        });
      });

    const send = (cmd: string, extra: Record<string, unknown> = {}) =>
      IPC.write(stringToBytes(JSON.stringify({ cmd, ...extra }) + '\n'));

    // Step 0 — the worklet booted at all (Bare runtime + JS bundle).
    const ready = await expect('ready');
    lines.push(`worklet boot: ${ready.ok ? 'OK' : 'FAIL'}`);

    // Step 1 — Hypercore append/read (exercises sodium + storage addons).
    // The worklet picks its own storage dir via bare-os (app sandbox tmpdir).
    const corePromise = expect('core');
    send('spike-core');
    const core = await corePromise;
    lines.push(
      core.ok
        ? `hypercore: OK (feed ${core.key?.slice(0, 16)}…, ${core.blocks} block)`
        : `hypercore: FAIL — ${core.err}`,
    );

    // Step 2 — Hyperswarm construction (exercises the udx addon).
    const swarmPromise = expect('swarm');
    send('spike-swarm');
    const swarm = await swarmPromise;
    lines.push(swarm.ok ? 'hyperswarm: OK' : `hyperswarm: FAIL — ${swarm.err}`);
  } catch (err) {
    lines.push(`spike aborted: ${String(err instanceof Error ? err.message : err)}`);
  } finally {
    worklet.terminate();
  }

  return lines.join('\n');
}
