// Harvest outbox datasource (PLAN-002 v2 C1) — RN side of the Bare worklet
// that owns the device's append-only case feed (the feed IS the outbox).
//
// Fire-and-forget BY CONTRACT, like CaseLogPort: a dead worklet or a failed
// append must never break the chat hot path — failures are logged and the
// case is simply not contributed (it still lives in SQLite; a later backfill
// can recover it).
//
// Consent: gated on the `contributeCases` opt-in toggle (default OFF), checked
// at contribution time so flipping the switch needs no restart. Privacy: the
// brief is redacted by construction (no VIN — brief-assembler + redact.ts);
// the id recipe and gate re-check live in the worklet and the hub
// (obdient-seed/PROTOCOL.md).

import { Worklet } from 'react-native-bare-kit';
import { useSettingsStore } from '@/store/settingsStore';
import {
  getLatestBriefBySession,
  getGatedSeniorTurn,
} from '@/data/datasources/storage.datasource';
import type { DiagnosticBrief } from '@/domain/entities/diagnostic-brief';
import type { GateResult } from '@/domain/services/diagnostic-gate';
// Generated by `npm run p2p:pack` — commit alongside the source.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — bare-pack emits an untyped ES module
import bundle from '../../../p2p/harvest-worklet.bundle.mjs';

export interface CaseContribution {
  readonly brief: DiagnosticBrief;
  readonly seniorAnswer: string;
  readonly gate: GateResult;
  readonly outcome?: 'yes' | 'no' | 'pending' | null;
}

interface WorkletReply {
  step: 'ready' | 'open' | 'append' | 'status' | 'core' | 'swarm';
  ok: boolean;
  id?: string;
  key?: string;
  length?: number;
  peers?: number;
  err?: string;
}

const REPLY_TIMEOUT_MS = 15_000;

// Pure-ASCII JSON protocol — byte-wise decode avoids TextDecoder (not
// guaranteed on Hermes) and untyped b4a on the RN side.
function bytesToString(data: unknown): string {
  if (typeof data === 'string') return data;
  const arr = data as Uint8Array;
  let s = '';
  for (let i = 0; i < arr.length; i++) s += String.fromCharCode(arr[i]!);
  return s;
}

// bare-kit IPC.write expects a TypedArray, never a plain string.
function stringToBytes(s: string): Uint8Array {
  const arr = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) arr[i] = s.charCodeAt(i) & 0xff;
  return arr;
}

export class HarvestOutboxDataSource {
  private worklet: Worklet | null = null;
  private startPromise: Promise<void> | null = null;
  private buffer = '';
  // FIFO of pending waiters per reply step (replies arrive in command order).
  private waiters = new Map<string, ((r: WorkletReply) => void)[]>();

  private expect(step: WorkletReply['step']): Promise<WorkletReply> {
    return new Promise((resolve, reject) => {
      const timer = setTimeout(
        () => reject(new Error(`harvest worklet: no '${step}' reply in ${REPLY_TIMEOUT_MS}ms`)),
        REPLY_TIMEOUT_MS,
      );
      const queue = this.waiters.get(step) ?? [];
      queue.push((r) => {
        clearTimeout(timer);
        resolve(r);
      });
      this.waiters.set(step, queue);
    });
  }

  private send(cmd: string, extra: Record<string, unknown> = {}): void {
    this.worklet?.IPC.write(stringToBytes(JSON.stringify({ cmd, ...extra }) + '\n'));
  }

  // Start the worklet once, open the persistent feed and join the harvest
  // swarm (client). Storage dir is chosen by the worklet (bare-os homedir).
  private ensureStarted(): Promise<void> {
    if (this.startPromise !== null) return this.startPromise;

    this.startPromise = (async () => {
      const worklet = new Worklet();
      this.worklet = worklet;

      worklet.IPC.on('data', (data: unknown) => {
        this.buffer += bytesToString(data);
        let idx: number;
        while ((idx = this.buffer.indexOf('\n')) >= 0) {
          const line = this.buffer.slice(0, idx);
          this.buffer = this.buffer.slice(idx + 1);
          try {
            const reply = JSON.parse(line) as WorkletReply;
            this.waiters.get(reply.step)?.shift()?.(reply);
          } catch {
            // ignore malformed lines
          }
        }
      });

      const ready = this.expect('ready');
      worklet.start('/harvest-worklet.bundle', bundle);
      await ready;

      const opened = this.expect('open');
      this.send('open', { swarm: true });
      const r = await opened;
      if (!r.ok) throw new Error(r.err ?? 'open failed');
      console.log(`[Harvest] outbox feed ${r.key?.slice(0, 16)}… (${r.length} blocks)`);
    })().catch((err) => {
      // Allow a later retry instead of caching the failure forever.
      this.startPromise = null;
      this.worklet?.terminate();
      this.worklet = null;
      throw err;
    });

    return this.startPromise;
  }

  /** Fire-and-forget: append one validated case to the outbox feed.
   *  No-op unless the user opted into `contributeCases`. */
  contributeCase(c: CaseContribution): void {
    if (!useSettingsStore.getState().contributeCases) return;

    void (async () => {
      await this.ensureStarted();
      const replied = this.expect('append');
      this.send('appendCase', {
        brief: c.brief,
        seniorAnswer: c.seniorAnswer,
        gate: c.gate,
        outcome: c.outcome ?? null,
      });
      const r = await replied;
      if (!r.ok) throw new Error(r.err ?? 'append failed');
      console.log(`[Harvest] case ${r.id?.slice(0, 12)}… appended (feed length ${r.length})`);
    })().catch((err) => console.warn('[Harvest] contribution failed:', err));
  }

  /** UX4 enrichment (fire-and-forget): re-contribute the session's case with
   *  its outcome. The id recipe hashes the SAME briefJson persisted at senior
   *  time, so the hub MERGES (outcome wins) instead of duplicating. */
  contributeOutcome(sessionId: string, outcome: 'yes' | 'no' | 'pending'): void {
    if (!useSettingsStore.getState().contributeCases) return;

    void (async () => {
      const brief = await getLatestBriefBySession(sessionId);
      const turn = await getGatedSeniorTurn(sessionId);
      if (brief == null || turn?.gateJson == null) return; // no senior case to enrich
      const gate = JSON.parse(turn.gateJson) as GateResult;
      if (gate.passed !== true) return; // the admission valve holds here too
      this.contributeCase({
        brief: JSON.parse(brief.briefJson) as DiagnosticBrief,
        seniorAnswer: turn.content,
        gate,
        outcome,
      });
    })().catch((err) => console.warn('[Harvest] outcome enrichment failed:', err));
  }

  /** Feed key/length/peer count — for a future Settings surface. */
  async status(): Promise<WorkletReply | null> {
    try {
      await this.ensureStarted();
      const replied = this.expect('status');
      this.send('status');
      return await replied;
    } catch {
      return null;
    }
  }
}

export const harvestOutbox = new HarvestOutboxDataSource();
