// Shared Bare worklet host (PLAN-002 v2 Fase B / C2).
//
// One Bare runtime serves BOTH P2P datasources (harvest outbox + distributed
// knowledge) so the phone pays for a single native runtime, not two. The
// worklet source is p2p/p2p-worklet.mjs; IPC is newline-delimited JSON,
// multiplexed by a `ns` field ('harvest' | 'knowledge').
//
// This host owns the singleton Worklet, the read buffer, and reply routing:
//   - request(ns, cmd, extra, replyStep) — send a command, await ITS reply
//     (FIFO of waiters keyed by `${ns}:${step}`, since replies arrive in order).
//   - on(ns, step, handler) — subscribe to UNSOLICITED pushes (knowledge
//     'chunk' ingest events, 'peer' churn events) that consume no waiter.
//
// Hermes-safe: byte-wise string <-> TypedArray (no TextDecoder/TextEncoder,
// not guaranteed on Hermes); IPC.write always gets a Uint8Array, never a string.

import { Worklet } from 'react-native-bare-kit';
import { Paths } from 'expo-file-system';
// Generated by `npm run p2p:pack` — commit alongside the source.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — bare-pack emits an untyped ES module
import bundle from '../../../p2p/p2p-worklet.bundle.mjs';

export type WorkletNs = 'harvest' | 'knowledge';

/** Absolute, writable, PERSISTENT directory for a Bare feed.
 *
 *  bare-os `homedir()` resolves to `/data` on Android — the data root, NOT the
 *  app's sandbox, so Hypercore ENOENTs trying to create a feed there. Only the
 *  RN side knows the app's writable document directory (expo-file-system), so it
 *  computes the path and passes it to the worklet on `open`. Strip the `file://`
 *  scheme (and any trailing slash): Hypercore needs a plain absolute path. */
export function persistentFeedDir(name: string): string {
  const base = Paths.document.uri.replace(/^file:\/\//, '').replace(/\/+$/, '');
  return `${base}/${name}`;
}

export interface WorkletReply {
  ns?: WorkletNs;
  step: string;
  ok: boolean;
  // Feature-specific fields (id, key, length, peers, chunk, peerId, err…).
  [field: string]: unknown;
}

const REPLY_TIMEOUT_MS = 15_000;

function bytesToString(data: unknown): string {
  if (typeof data === 'string') return data;
  const arr = data as Uint8Array;
  let s = '';
  for (let i = 0; i < arr.length; i++) s += String.fromCharCode(arr[i]!);
  return s;
}

function stringToBytes(s: string): Uint8Array {
  const arr = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) arr[i] = s.charCodeAt(i) & 0xff;
  return arr;
}

class WorkletHost {
  private worklet: Worklet | null = null;
  private startPromise: Promise<void> | null = null;
  private buffer = '';
  // FIFO of pending one-shot waiters, keyed by `${ns}:${step}` (or `ready`).
  private waiters = new Map<string, ((r: WorkletReply) => void)[]>();
  // Persistent subscribers for unsolicited pushes, keyed by `${ns}:${step}`.
  private listeners = new Map<string, (r: WorkletReply) => void>();

  /** Start the worklet once and wait for its boot `ready`. Idempotent. */
  start(): Promise<void> {
    if (this.startPromise !== null) return this.startPromise;

    this.startPromise = (async () => {
      const worklet = new Worklet();
      this.worklet = worklet;

      worklet.IPC.on('data', (data: unknown) => {
        this.buffer += bytesToString(data);
        let idx: number;
        while ((idx = this.buffer.indexOf('\n')) >= 0) {
          const line = this.buffer.slice(0, idx);
          this.buffer = this.buffer.slice(idx + 1);
          if (!line) continue;
          let reply: WorkletReply;
          try {
            reply = JSON.parse(line) as WorkletReply;
          } catch {
            continue; // ignore malformed lines
          }
          this.route(reply);
        }
      });

      const ready = this.expectKey('ready');
      worklet.start('/p2p-worklet.bundle', bundle);
      await ready;
    })().catch((err) => {
      // Allow a later retry instead of caching the failure forever.
      this.startPromise = null;
      this.worklet?.terminate();
      this.worklet = null;
      throw err;
    });

    return this.startPromise;
  }

  /** Send `cmd` in namespace `ns` and await the reply whose step is `replyStep`. */
  async request(
    ns: WorkletNs,
    cmd: string,
    extra: Record<string, unknown> = {},
    replyStep = cmd,
  ): Promise<WorkletReply> {
    await this.start();
    const replied = this.expectKey(`${ns}:${replyStep}`);
    this.send(ns, cmd, extra);
    return replied;
  }

  /** Subscribe to an unsolicited push (e.g. knowledge 'chunk'/'peer'). */
  on(ns: WorkletNs, step: string, handler: (r: WorkletReply) => void): void {
    this.listeners.set(`${ns}:${step}`, handler);
  }

  /** Fire-and-forget send (no reply awaited). */
  send(ns: WorkletNs, cmd: string, extra: Record<string, unknown> = {}): void {
    this.worklet?.IPC.write(stringToBytes(JSON.stringify({ ns, cmd, ...extra }) + '\n'));
  }

  // --- Private ---

  private route(reply: WorkletReply): void {
    // Boot `ready` carries no ns; feature replies/pushes are `${ns}:${step}`.
    const key = reply.ns ? `${reply.ns}:${reply.step}` : reply.step;
    const listener = this.listeners.get(key);
    if (listener) {
      listener(reply);
      return;
    }
    this.waiters.get(key)?.shift()?.(reply);
  }

  private expectKey(key: string): Promise<WorkletReply> {
    return new Promise((resolve, reject) => {
      const timer = setTimeout(
        () => reject(new Error(`worklet: no '${key}' reply in ${REPLY_TIMEOUT_MS}ms`)),
        REPLY_TIMEOUT_MS,
      );
      const queue = this.waiters.get(key) ?? [];
      queue.push((r) => {
        clearTimeout(timer);
        resolve(r);
      });
      this.waiters.set(key, queue);
    });
  }
}

export const workletHost = new WorkletHost();
