// Shared Bare worklet host (PLAN-002 v2 Fase B / C2).
//
// One Bare runtime serves BOTH P2P datasources (harvest outbox + distributed
// knowledge) so the phone pays for a single native runtime, not two. The
// worklet source is p2p/p2p-worklet.mjs; IPC is newline-delimited JSON,
// multiplexed by a `ns` field ('harvest' | 'knowledge').
//
// This host owns the singleton Worklet, the read buffer, and reply routing:
//   - request(ns, cmd, extra, replyStep) — send a command, await ITS reply
//     (FIFO of waiters keyed by `${ns}:${step}`, since replies arrive in order).
//   - on(ns, step, handler) — subscribe to UNSOLICITED pushes (knowledge
//     'chunk' ingest events, 'peer' churn events) that consume no waiter.
//
// Hermes-safe UTF-8 <-> TypedArray, hand-rolled (TextEncoder/TextDecoder are not
// guaranteed on Hermes). MUST be real UTF-8, not byte-truncation: the worklet
// encodes/decodes UTF-8 (b4a), and a payload like a senior answer carries
// non-ASCII (bullets •, dashes —, °, accents). A naive `charCodeAt & 0xff` maps
// e.g. `•` (U+2022) to 0x22 (`"`) or some chars to 0x0A (`\n`), injecting
// spurious quotes/newlines that break the JSON framing → the worklet drops the
// line → the request never gets a reply → a 15s timeout. Proper UTF-8 keeps
// every non-delimiter byte in 0x80–0xBF, so the `\n` framing stays intact.

import { Worklet } from 'react-native-bare-kit';
import { Paths } from 'expo-file-system';
// Generated by `npm run p2p:pack` — commit alongside the source.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — bare-pack emits an untyped ES module
import bundle from '../../../p2p/p2p-worklet.bundle.mjs';

export type WorkletNs = 'harvest' | 'knowledge';

/** Absolute, writable, PERSISTENT directory for a Bare feed.
 *
 *  bare-os `homedir()` resolves to `/data` on Android — the data root, NOT the
 *  app's sandbox, so Hypercore ENOENTs trying to create a feed there. Only the
 *  RN side knows the app's writable document directory (expo-file-system), so it
 *  computes the path and passes it to the worklet on `open`. Strip the `file://`
 *  scheme (and any trailing slash): Hypercore needs a plain absolute path. */
export function persistentFeedDir(name: string): string {
  const base = Paths.document.uri.replace(/^file:\/\//, '').replace(/\/+$/, '');
  return `${base}/${name}`;
}

export interface WorkletReply {
  ns?: WorkletNs;
  step: string;
  ok: boolean;
  // Feature-specific fields (id, key, length, peers, chunk, peerId, err…).
  [field: string]: unknown;
}

const REPLY_TIMEOUT_MS = 15_000;

// Decode UTF-8 bytes → string (mirrors b4a.toString(buf, 'utf8') in the worklet).
function bytesToString(data: unknown): string {
  if (typeof data === 'string') return data;
  const arr = data as Uint8Array;
  let s = '';
  let i = 0;
  while (i < arr.length) {
    const b0 = arr[i++]!;
    if (b0 < 0x80) {
      s += String.fromCharCode(b0);
    } else if (b0 < 0xe0) {
      const b1 = arr[i++]! & 0x3f;
      s += String.fromCharCode(((b0 & 0x1f) << 6) | b1);
    } else if (b0 < 0xf0) {
      const b1 = arr[i++]! & 0x3f;
      const b2 = arr[i++]! & 0x3f;
      s += String.fromCharCode(((b0 & 0x0f) << 12) | (b1 << 6) | b2);
    } else {
      const b1 = arr[i++]! & 0x3f;
      const b2 = arr[i++]! & 0x3f;
      const b3 = arr[i++]! & 0x3f;
      const cp = (((b0 & 0x07) << 18) | (b1 << 12) | (b2 << 6) | b3) - 0x10000;
      s += String.fromCharCode(0xd800 + (cp >> 10), 0xdc00 + (cp & 0x3ff));
    }
  }
  return s;
}

// Encode string → UTF-8 bytes (mirrors b4a.from(str, 'utf8') in the worklet).
function stringToBytes(s: string): Uint8Array {
  const bytes: number[] = [];
  for (let i = 0; i < s.length; i++) {
    let code = s.charCodeAt(i);
    // Combine a surrogate pair into a single code point.
    if (code >= 0xd800 && code <= 0xdbff && i + 1 < s.length) {
      const next = s.charCodeAt(i + 1);
      if (next >= 0xdc00 && next <= 0xdfff) {
        code = 0x10000 + ((code - 0xd800) << 10) + (next - 0xdc00);
        i++;
      }
    }
    if (code < 0x80) {
      bytes.push(code);
    } else if (code < 0x800) {
      bytes.push(0xc0 | (code >> 6), 0x80 | (code & 0x3f));
    } else if (code < 0x10000) {
      bytes.push(0xe0 | (code >> 12), 0x80 | ((code >> 6) & 0x3f), 0x80 | (code & 0x3f));
    } else {
      bytes.push(
        0xf0 | (code >> 18),
        0x80 | ((code >> 12) & 0x3f),
        0x80 | ((code >> 6) & 0x3f),
        0x80 | (code & 0x3f),
      );
    }
  }
  return new Uint8Array(bytes);
}

class WorkletHost {
  private worklet: Worklet | null = null;
  private startPromise: Promise<void> | null = null;
  private buffer = '';
  // FIFO of pending one-shot waiters, keyed by `${ns}:${step}` (or `ready`).
  private waiters = new Map<string, ((r: WorkletReply) => void)[]>();
  // Persistent subscribers for unsolicited pushes, keyed by `${ns}:${step}`.
  private listeners = new Map<string, (r: WorkletReply) => void>();

  /** Start the worklet once and wait for its boot `ready`. Idempotent. */
  start(): Promise<void> {
    if (this.startPromise !== null) return this.startPromise;

    this.startPromise = (async () => {
      const worklet = new Worklet();
      this.worklet = worklet;

      worklet.IPC.on('data', (data: unknown) => {
        this.buffer += bytesToString(data);
        let idx: number;
        while ((idx = this.buffer.indexOf('\n')) >= 0) {
          const line = this.buffer.slice(0, idx);
          this.buffer = this.buffer.slice(idx + 1);
          if (!line) continue;
          let reply: WorkletReply;
          try {
            reply = JSON.parse(line) as WorkletReply;
          } catch {
            continue; // ignore malformed lines
          }
          this.route(reply);
        }
      });

      const ready = this.expectKey('ready');
      worklet.start('/p2p-worklet.bundle', bundle);
      await ready;
    })().catch((err) => {
      // Allow a later retry instead of caching the failure forever.
      this.startPromise = null;
      this.worklet?.terminate();
      this.worklet = null;
      throw err;
    });

    return this.startPromise;
  }

  /** Send `cmd` in namespace `ns` and await the reply whose step is `replyStep`. */
  async request(
    ns: WorkletNs,
    cmd: string,
    extra: Record<string, unknown> = {},
    replyStep = cmd,
  ): Promise<WorkletReply> {
    await this.start();
    const replied = this.expectKey(`${ns}:${replyStep}`);
    this.send(ns, cmd, extra);
    return replied;
  }

  /** Subscribe to an unsolicited push (e.g. knowledge 'chunk'/'peer'). */
  on(ns: WorkletNs, step: string, handler: (r: WorkletReply) => void): void {
    this.listeners.set(`${ns}:${step}`, handler);
  }

  /** Fire-and-forget send (no reply awaited). */
  send(ns: WorkletNs, cmd: string, extra: Record<string, unknown> = {}): void {
    this.worklet?.IPC.write(stringToBytes(JSON.stringify({ ns, cmd, ...extra }) + '\n'));
  }

  // --- Private ---

  private route(reply: WorkletReply): void {
    // Boot `ready` carries no ns; feature replies/pushes are `${ns}:${step}`.
    const key = reply.ns ? `${reply.ns}:${reply.step}` : reply.step;
    const listener = this.listeners.get(key);
    if (listener) {
      listener(reply);
      return;
    }
    this.waiters.get(key)?.shift()?.(reply);
  }

  private expectKey(key: string): Promise<WorkletReply> {
    return new Promise((resolve, reject) => {
      const timer = setTimeout(
        () => reject(new Error(`worklet: no '${key}' reply in ${REPLY_TIMEOUT_MS}ms`)),
        REPLY_TIMEOUT_MS,
      );
      const queue = this.waiters.get(key) ?? [];
      queue.push((r) => {
        clearTimeout(timer);
        resolve(r);
      });
      this.waiters.set(key, queue);
    });
  }
}

export const workletHost = new WorkletHost();
